### ISSUE TITLE
Possible bug with multiple channels

### ISSUE THREAD

**Issue by AMessiah** [member-gentei/member-gentei#147]
Hello,

Currently your app does not show I am a member of some channels even though youtube shows that everything is fine.

Youtube has the possibility of having multiple "brand accounts" under the same email, and all of them can see the membership content but only the one that was used to enter the membership can like/comment on videos, vote etc.

What I am suspecting is that somehow the issue I'm having has to do with this, as I entered membership through a brand account and not my main youtube account. I can provide additional details if you want (through here or discord).

PS: I did use the brand account when linking to gentei

**Comment by mark-ignacio** [comment]
The membership check issue was most likely fixed by the hotfix in 5c0805e.
