### ISSUE TITLE
Unlink Discord account associated with a YouTube account?

### ISSUE THREAD

**Issue by dasBente** [member-gentei/member-gentei#217]
We've encountered the following situation:  
A user opened a ticket on our fan server notifying us that they couldn't apply for their membership role via gentei as their YouTube account seems to already be linked with another Discord account not of their own. They've told us that they had issues with malware some time ago.  
We assume their YouTube account might have at some point gotten hijacked and the attacker possibly linked their own account with the user's YouTube. We've since verified that they seem to be in possession of a legitimate membership and the user they alleged to have been coupled with their YouTube account seems to only be in possession of the gentei membership role and no others (especially not the general member role needed to access most channels).

Is there any way to unlink a coupled YouTube account for situations like this?

**Comment by mark-ignacio** [comment]
The best way to currently handle this is for the user in question to revoke Gentei's permission on their YouTube account. During the daily membership check, Gentei should diassociate the YouTube and Discord account, which should "free up" the YouTube account for their new Discord user. Screenshot of what this user should be looking for is below.

Google's instructions to do so are here: https://support.google.com/accounts/answer/3466521

**Comment by Mylllles** [comment]
Hi, I'd like to reopen this issue. I am facing a similar situation, however the suggested solution did not work.

My Youtube account has been linked to a Discord account that I don't have access to anymore. I tried revoking Gentei's access permissions and waiting a few days as described (multiple times), but it did not free up the accounts, it still says that my Youtube account is already in use. 

I have complete access to the Youtube/Google account in question, but no access whatsoever to the Discord account it used to be linked to. Is there something that can be done about this?
