### ISSUE TITLE
Unlink Discord account associated with a YouTube account

### ISSUE THREAD

**Issue by Mylllles** [member-gentei/member-gentei#294]
Hi, I'd like to reopen this issue mentioned in #217. I am facing a similar situation, however the suggested solution in that issue did not work.

My Youtube account was linked to a Discord account that I don't have access to anymore. I tried revoking Gentei's access permissions and waiting a few days as described, even weeks (multiple times), but it did not free up the account, it still says that my Youtube account is already in use.

I have complete access to the Youtube/Google account in question, but no access whatsoever to the Discord account it used to be linked to. Is there something that can be done about this?

**Comment by mark-ignacio** [comment]
For individual account issues, please use the #gentei-限定 channel or DM me on Discord.
