### ISSUE TITLE
Bot is not correctly detecting memberships for a single channel

### ISSUE THREAD

**Issue by Syampuuh** [member-gentei/member-gentei#346]
![image](https://github.com/user-attachments/assets/ac146723-ea5c-47b6-9dad-567463c904bd)
![image](https://github.com/user-attachments/assets/e29552ed-1ecd-4f3e-91c5-d681c38719ad)
![image](https://github.com/user-attachments/assets/45d92e29-1cf9-4858-ad36-3ea839624adc)

For some reason, the bot is not detecting mine or others' membership to [Hikasa Tomoshika's channel.](https://www.youtube.com/channel/UC3vzVK_N_SUVKqbX69L_X4g) It is properly configured, and the only thing that stands out from the other channels that it is working fine with is that she has enabled English translations of her account info, ie. her display name is simplified and the bio displays in English. No clue how or why that could affect things, but I figure it bears mentioning as the only obvious difference.

**Comment by mark-ignacio** [comment]
For people searching: by sheer bad luck, Gentei auto-selected a video associated with a higher membership tier. This has been resolved by me manually switching the video out, so please reach out on Discord to help coordinate that!
